Version 1.2.3
dji-sdk/Android-Bridge-App pull request #6
Opened 2018-03-27 18:42 UTC by hpimentel

- Prevent ConcurrentModificationException with synchronization
- Prevent sending data when there are no active connections
- Add heart beat
- New remote logging to work with bridge monitor

2018-03-29 00:40 UTC, talobin commented on android-wsbridge/app/src/main/java/com/dji/wsbridge/lib/DJILogger.java
> +    private static final String REMOTE_LOGGER_URL = "";
Should add something like
"your_url_goes_here.com"

2018-03-29 00:40 UTC, talobin commented on android-wsbridge/app/build.gradle
> +    compile 'org.java-websocket:java-websocket:1.3.1'
Is it backward change necessary?

2018-03-29 00:55 UTC, hpimentel commented on android-wsbridge/app/build.gradle
> +    compile 'org.java-websocket:java-websocket:1.3.1'
I looked into this and found that in our private repo the library has never been at 1.3.3.
So it was changed in the public repo but not the private one. I'll do some testing to see if it causes any issues and I'll put it back.

2018-03-29 22:30 UTC, talobin requested changes

2018-03-29 22:30 UTC, talobin commented on android-wsbridge/app/build.gradle
> -    compile 'org.java-websocket:java-websocket:1.3.3'
Should probably keep this higher version

2018-03-29 22:30 UTC, talobin commented on android-wsbridge/app/src/main/java/com/dji/wsbridge/BridgeActivity.java
> -    public void onWSTrafficEvent(WSConnectionManager.WSTrafficEvent event) {
Should add back this logic.

2018-04-05 00:49 UTC, talobin approved these changes

2018-04-05 00:49 UTC, talobin commented on android-wsbridge/app/src/main/java/com/dji/wsbridge/BridgeActivity.java
> -            if (isWSConnected.compareAndSet(false, true)) {
Keep this logic

2018-04-05 00:49 UTC, talobin commented on android-wsbridge/app/src/main/java/com/dji/wsbridge/lib/connection/WSConnectionManager.java
> -    public void onStart() {
Keep this

2018-04-05 00:49 UTC, talobin commented on android-wsbridge/app/src/main/java/com/dji/wsbridge/lib/connection/WSConnectionManager.java
> -                    if (conn instanceof WebSocketImpl && ((WebSocketImpl) conn).outQueue.size() > maxBufferSizePerConnection) {
Keep this

2018-04-05 00:50 UTC, merged